[package]
name = "nvml-rs"
version = "0.1.0"
authors = ["sihao"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = [
    "nvml-sys",
]

